# Installing and Importing NumPy

In [ ]:
## https://github.com/numpy/numpy

In [ ]:
##!conda install numpy --y

In [1]:
import numpy as np

# Creating a simple NumPy array using np.array

In [2]:
python_list = ['a',100,0.5]
print(python_list)



['a', 100, 0.5]


In [3]:
numpy_array = np.array([1,2,3])
numpy_array

array([1, 2, 3])

In [4]:
type(numpy_array)

numpy.ndarray

In [5]:
type(numpy_array[0])

numpy.int64

# Types of Arrays and Visualization

In [7]:
## 1D Array, 2D Array, 3D or nD
a = np.array([1,2,3])

a.shape


(3,)

In [10]:
two_array = np.array([[1,2,3],[4,5,6]])
two_array

two_array.shape

(2, 3)

In [12]:
three_array = np.array([[[1,2,3],[4,5,6],[6,7,8]]])
three_array

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [13]:
three_array.shape

(1, 3, 3)

In [15]:
a[0]

1

# Array Initialization

In [18]:
zeros = np.zeros((1,2))
zeros
print(zeros, zeros.shape)

[[0. 0.]] (1, 2)


In [19]:
ones = np.ones((1,2))
print(ones,ones.shape)

[[1. 1.]] (1, 2)


# Arranging Numbers Between 2 Values with Interval of X - arange

In [21]:
## Line Segment

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a = np.arange(0,20,4)
a

array([ 0,  4,  8, 12, 16])

In [24]:
negative = np.arange(-1,-10,-2)
negative

array([-1, -3, -5, -7, -9])

# Arranging 'z' Numbers Between 2 Values - linspace

In [27]:
## Converse of arange

lin_space = np.linspace(0,10,6)
lin_space

array([ 0.,  2.,  4.,  6.,  8., 10.])

# Creating Arrays of N Dimension Using Same Numbers - fill

In [31]:
fill_array = np.full((2,2),5)
fill_array

array([[5, 5],
       [5, 5]])

# Creating Arrays of N Dimension Using Random Numbers - random.random

In [32]:
random = np.random.random((2,2))
random

array([[0.07708899, 0.97578526],
       [0.08130605, 0.42821473]])

# Creating Arrays of N Dimension Using Random Numbers - random.randint

In [140]:
randint = np.random.randint(low=0,high=10,size=(15,2))
randint

array([[5, 4],
       [1, 2],
       [1, 6],
       [2, 9],
       [2, 1],
       [4, 3],
       [6, 5],
       [8, 3],
       [3, 8],
       [9, 2],
       [6, 1],
       [0, 1],
       [7, 4],
       [0, 1],
       [7, 6]])

# Finding Shape of an Array - np.shape

In [37]:
print(a)

a.shape

[ 0  4  8 12 16]


(5,)

# Reshaping an Array - np.shape

In [44]:
a = np.arange(24)
# print(a)



[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]


In [45]:
a.shape = (12,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

# Reshaping an Array - reshape

In [47]:
b = a.reshape(6,2,2)
print(b)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]


# Finding Size of an Array - size

In [48]:
a = np.arange(24)

In [51]:
b = np.arange(24).reshape(12,2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [49]:
a.size

24

In [52]:
len(b)

12

# Finding Dimension of an Array - ndim

In [53]:
b.ndim


2

# Finding Data Type of an Array - dtype

In [56]:
a
print(a)
a.dtype

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


dtype('int64')

# Addition in NumPy Array - np.sum

In [57]:
np.sum([[1,2],[2,3]])

8

In [58]:
np.sum([[1,2],[2,3]],axis=0)

array([3, 5])

In [59]:
np.sum([[1,2],[2,3]],axis=1)

array([3, 5])

# Subtraction in NumPy Array - np.subtract

In [62]:
a = np.array([3,2])
b = np.array([1,1])


np.subtract(a,b)

array([2, 1])

# Division in NumPy Array - np.divide

In [63]:
a = np.array([3,2])
b = np.array([1,1])

np.divide(a,b)

array([3., 2.])

# Mulitplication in NumPy Array - np.multiply

In [64]:
np.multiply(a,b)

array([3, 2])

# Exponential Operations in NumPy Array - np.exp

In [67]:
a = np.array([1,1])

print(np.exp(a))

e^a === e is euler's number -- log base --

[2.71828183 2.71828183]


# Square Root Operations in NumPy Array - np.sqrt

In [68]:
a = np.arange(3)
a


array([0, 1, 2])

In [69]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356])

#  Sin Operations in NumPy Array - np.sin

In [70]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743])

# Cos Operations in NumPy Array - np.cos

In [71]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684])

# Log Operations in NumPy Array - np.log

In [72]:
np.log(a)

<ipython-input-72-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

# Element Wise Array Comparision - np.equal

In [79]:
a = np.arange(6)
b = np.array([0,1,2,3,4,6])

print(a)
print(b)

[0 1 2 3 4 5]
[0 1 2 3 4 6]


In [76]:
np.equal(a,b)

array([ True,  True,  True,  True,  True,  True])

# Array Wise Comparision - np.array_equal

In [80]:
np.array_equal(a,b)

False

# Aggregate Functions - Sum, Min, Mean, Median, Correlation Co-efficient, Standard Deviation

In [81]:
print(a)

[0 1 2 3 4 5]


In [85]:
np.std(a)

1.707825127659933

# BroadCasting

In [86]:
## Scalar and 1D Array

a = np.array([1,2,3])
b = 2

a + b

array([3, 4, 5])

In [87]:
## Scalar and 2D Array

a = np.array([[1,2,3],[4,5,6]])
b = 2

a + b

array([[3, 4, 5],
       [6, 7, 8]])

# Indexing and Slicing - Python and Numpy

In [95]:
a = ['a','b','c','d','e']
print(a)

a[0]

['a', 'b', 'c', 'd', 'e']


'a'

In [89]:
a[2]

'c'

In [90]:
a[1:4]

1 -- taken into consideration
4 is not

['b', 'c', 'd']

In [91]:
a[-5:-2]

['a', 'b', 'c']

# Indexing and Slicing in 2D Array

In [97]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
a[0]

array([1, 2, 3])

In [99]:
a[1,1]

5

In [100]:
a[:2,:1]
## a[row,column]

array([[1],
       [4]])

In [101]:
a[2]

array([7, 8, 9])

In [102]:
a[2,:]

array([7, 8, 9])

# Array Concatenation

In [108]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Stacking Arrays Vertically

In [111]:
c = np.vstack((a,b))

print(c)
print(c.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


# Stacking Arrays Horizontally

In [112]:
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

# Combining Column Wise - Stacked Array

In [113]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

# Splitting Arrays - Horizontally

In [12]:
x = np.arange(16)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [13]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
y = x.reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
z = np.hsplit(y, 2)

In [21]:
z

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# Splitting Arrays - Vertically

In [130]:
np.vsplit(y,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# Advantage of NumPy over List - Comparison of Speed and Memory

In [132]:
## Memory 

import sys

py_array = range(1000)

print("Size of each element in the python list in bytes is:", sys.getsizeof(py_array))

print("Size of entire python array/list in bytes is:", sys.getsizeof(py_array)*len(py_array))

Size of each element in the python list in bytes is: 48
Size of entire python array/list in bytes is: 48000


In [133]:
np_array = np.arange(1000)

print("Size of each element in the numpy array is:", np_array.itemsize)

print("Size of all the elements in the numpy array is: ", np_array.itemsize * np_array.size)

Size of each element in the numpy array is: 8
Size of all the elements in the numpy array is:  8000


In [ ]:
## Vectorization
## Multiprocessing

In [135]:
## Speed

import time

list_1 = range(1000)
list_2 = range(1000)


np_array1 = np.arange(1000)
np_array2 = np.arange(1000)


initial_time = time.time()

resultant_list = [(a*b) for a , b in zip(list_1,list_2)]

print("Total time taken for resulting list based on python is:", (time.time()-initial_time),"seconds")

Total time taken for resulting list based on python is: 0.0002319812774658203 seconds


In [136]:
initial_time = time.time()

resultant_array = np_array1 * np_array2

print("Total time taken for resultant array based on NumPy is:", (time.time()-initial_time),"seconds")

Total time taken for resultant array based on NumPy is: 0.0001430511474609375 seconds


In [1]:
import numpy as np

In [6]:
a = np.array([[1,2,3,4,5,5]])

In [8]:
a.shape

(1, 6)

In [25]:
b = np.array([15, 16, 17, 19, 20, 21])

In [26]:
a*b

array([[ 15,  32,  51,  76, 100, 105]])